export enum IssueStatus {
    OPEN = 'OPEN',
    ASSIGNED = 'ASSIGNED',
    IN_PROGRESS = 'IN_PROGRESS',
    VISIT_SCHEDULED='VISIT_SCHEDULED',
    RESOLVED = 'RESOLVED',
    PAID='PAID',
    WAITING_FOR_PARTS='WAITING_FOR_PARTS',
    INVOICE_GENERATED='INVOICE_GENERATED',
    CANCELLED = 'CANCELLED',
}